Feature layout
franciscojsc/calculadora-ip pull request #9
Opened 2020-04-10 18:28 UTC by alex-chaves

Alterei o layout da página, criei caixas personalizadas para o resultado com efeito flutuante e o deixei responsivo.

2020-04-10 20:48 UTC, franciscojsc requested changes

2020-04-10 20:48 UTC, franciscojsc commented on src/css/style.css
> +input {
Poderia adicionar uma cor de fundo para os campos de entradas? Para ajudar na visualização.

2020-04-10 20:48 UTC, franciscojsc commented on src/index.html
> +        </section>
Como o bloco de resultado está sendo usado somente quando é realizado o cálculo. Adicione o bloco de resultado via JavaScript.

2020-04-10 20:48 UTC, franciscojsc commented on src/js/script.js
> +      </div>`;
Poderia criar uma função que devolver o HTML para diminuir repetição de código.

2020-04-10 20:48 UTC, franciscojsc commented on src/js/script.js
> +      $resultClasse.innerHTML = "<div class='card'><p style='color:red' >Verifique a máscara</p></div>";
Criar um estilo personalizado para caixa de erro.

2020-04-13 16:52 UTC, alex-chaves commented on src/css/style.css
> +input {
Certo, irei adicionar um cinza claro.

2020-04-13 17:57 UTC, alex-chaves commented on src/index.html
> +        </section>
Ok.

2020-04-14 18:21 UTC, alex-chaves commented on src/js/script.js
> +      </div>`;
Beleza.

2020-04-14 19:35 UTC, alex-chaves commented on src/js/script.js
> +      $resultClasse.innerHTML = "<div class='card'><p style='color:red' >Verifique a máscara</p></div>";
Certo, criei uma caixa para notificar quando o usuário inserir dados incorretos.

2020-04-14 21:29 UTC, franciscojsc commented on src/js/script.js
> +      $resultClasse.innerHTML = "<div class='card'><p style='color:red' >Verifique a máscara</p></div>";
Ok

2020-04-14 21:35 UTC, franciscojsc commented
Ficou muito bom! :+1:  Obrigado!!!

2020-04-14 21:35 UTC, merged